package com.spoon.demo.model;

import java.math.BigDecimal;

import com.spoon.demo.model.enums.Category;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
public class Recipe {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long recipeID;

    @Column(nullable = false)
    @NotBlank(message = "Recipe name is required")
    private String name;

    @Column(nullable = false)
    @NotNull(message = "Recipe time is required")
    private Long time;

    @Column(nullable = true)
    private String imagePath;

    @Enumerated(EnumType.STRING)
    private Category category;

    @Column(columnDefinition = "TEXT", nullable = false)
    @NotBlank(message = "Description is required")
    private String description;

    @Column(columnDefinition = "TEXT")
    private String ingredients;

    @Column(columnDefinition = "TEXT", nullable = false)
    @NotBlank(message = "Steps are required")
    private String steps;

    @Column(nullable = false)
    @NotBlank(message = "Author is required")
    private String author;

    @Column(nullable = false)
    private long likesCount;

    @Column(nullable = true)
    private BigDecimal rating;

    @Column(nullable = true)
    private String videoUrl;

    // Getters and Setters (generated by Lombok)
}
